// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: czkatran.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CzKatranServiceClient is the client API for CzKatranService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CzKatranServiceClient interface {
	ChangeMac(ctx context.Context, in *Mac, opts ...grpc.CallOption) (*Bool, error)
	GetMac(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Mac, error)
	AddVip(ctx context.Context, in *VipMeta, opts ...grpc.CallOption) (*Bool, error)
	DelVip(ctx context.Context, in *Vip, opts ...grpc.CallOption) (*Bool, error)
	GetAllVips(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Vips, error)
	ModifyVip(ctx context.Context, in *VipMeta, opts ...grpc.CallOption) (*Bool, error)
	ModifyReal(ctx context.Context, in *RealMeta, opts ...grpc.CallOption) (*Bool, error)
	GetVipFlags(ctx context.Context, in *Vip, opts ...grpc.CallOption) (*Flags, error)
	GetRealFlags(ctx context.Context, in *Real, opts ...grpc.CallOption) (*Flags, error)
	AddRealForVip(ctx context.Context, in *RealForVip, opts ...grpc.CallOption) (*Bool, error)
	DelRealForVip(ctx context.Context, in *RealForVip, opts ...grpc.CallOption) (*Bool, error)
	ModifyRealsForVip(ctx context.Context, in *ModifiedRealForVip, opts ...grpc.CallOption) (*Bool, error)
	GetRealsForVip(ctx context.Context, in *Vip, opts ...grpc.CallOption) (*Reals, error)
	ModifyQuicRealsMapping(ctx context.Context, in *ModifiedQuicReals, opts ...grpc.CallOption) (*Bool, error)
	GetQuicRealsMapping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*QuicReals, error)
	GetStatsForVip(ctx context.Context, in *Vip, opts ...grpc.CallOption) (*Stats, error)
	GetLruStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Stats, error)
	GetLruMissStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Stats, error)
	GetLruFailbackStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Stats, error)
	GetIcmpTooBigStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Stats, error)
	AddHealthcheckerDst(ctx context.Context, in *Healthcheck, opts ...grpc.CallOption) (*Bool, error)
	DelHealthcheckerDst(ctx context.Context, in *Somark, opts ...grpc.CallOption) (*Bool, error)
	GetHealthcheckersDst(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HcMap, error)
}

type czKatranServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCzKatranServiceClient(cc grpc.ClientConnInterface) CzKatranServiceClient {
	return &czKatranServiceClient{cc}
}

func (c *czKatranServiceClient) ChangeMac(ctx context.Context, in *Mac, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/lb.czkatran.czKatranService/changeMac", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *czKatranServiceClient) GetMac(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Mac, error) {
	out := new(Mac)
	err := c.cc.Invoke(ctx, "/lb.czkatran.czKatranService/getMac", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *czKatranServiceClient) AddVip(ctx context.Context, in *VipMeta, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/lb.czkatran.czKatranService/addVip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *czKatranServiceClient) DelVip(ctx context.Context, in *Vip, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/lb.czkatran.czKatranService/delVip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *czKatranServiceClient) GetAllVips(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Vips, error) {
	out := new(Vips)
	err := c.cc.Invoke(ctx, "/lb.czkatran.czKatranService/getAllVips", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *czKatranServiceClient) ModifyVip(ctx context.Context, in *VipMeta, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/lb.czkatran.czKatranService/modifyVip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *czKatranServiceClient) ModifyReal(ctx context.Context, in *RealMeta, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/lb.czkatran.czKatranService/modifyReal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *czKatranServiceClient) GetVipFlags(ctx context.Context, in *Vip, opts ...grpc.CallOption) (*Flags, error) {
	out := new(Flags)
	err := c.cc.Invoke(ctx, "/lb.czkatran.czKatranService/getVipFlags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *czKatranServiceClient) GetRealFlags(ctx context.Context, in *Real, opts ...grpc.CallOption) (*Flags, error) {
	out := new(Flags)
	err := c.cc.Invoke(ctx, "/lb.czkatran.czKatranService/getRealFlags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *czKatranServiceClient) AddRealForVip(ctx context.Context, in *RealForVip, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/lb.czkatran.czKatranService/addRealForVip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *czKatranServiceClient) DelRealForVip(ctx context.Context, in *RealForVip, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/lb.czkatran.czKatranService/delRealForVip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *czKatranServiceClient) ModifyRealsForVip(ctx context.Context, in *ModifiedRealForVip, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/lb.czkatran.czKatranService/modifyRealsForVip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *czKatranServiceClient) GetRealsForVip(ctx context.Context, in *Vip, opts ...grpc.CallOption) (*Reals, error) {
	out := new(Reals)
	err := c.cc.Invoke(ctx, "/lb.czkatran.czKatranService/getRealsForVip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *czKatranServiceClient) ModifyQuicRealsMapping(ctx context.Context, in *ModifiedQuicReals, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/lb.czkatran.czKatranService/modifyQuicRealsMapping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *czKatranServiceClient) GetQuicRealsMapping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*QuicReals, error) {
	out := new(QuicReals)
	err := c.cc.Invoke(ctx, "/lb.czkatran.czKatranService/getQuicRealsMapping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *czKatranServiceClient) GetStatsForVip(ctx context.Context, in *Vip, opts ...grpc.CallOption) (*Stats, error) {
	out := new(Stats)
	err := c.cc.Invoke(ctx, "/lb.czkatran.czKatranService/getStatsForVip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *czKatranServiceClient) GetLruStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Stats, error) {
	out := new(Stats)
	err := c.cc.Invoke(ctx, "/lb.czkatran.czKatranService/getLruStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *czKatranServiceClient) GetLruMissStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Stats, error) {
	out := new(Stats)
	err := c.cc.Invoke(ctx, "/lb.czkatran.czKatranService/getLruMissStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *czKatranServiceClient) GetLruFailbackStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Stats, error) {
	out := new(Stats)
	err := c.cc.Invoke(ctx, "/lb.czkatran.czKatranService/getLruFailbackStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *czKatranServiceClient) GetIcmpTooBigStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Stats, error) {
	out := new(Stats)
	err := c.cc.Invoke(ctx, "/lb.czkatran.czKatranService/getIcmpTooBigStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *czKatranServiceClient) AddHealthcheckerDst(ctx context.Context, in *Healthcheck, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/lb.czkatran.czKatranService/addHealthcheckerDst", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *czKatranServiceClient) DelHealthcheckerDst(ctx context.Context, in *Somark, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/lb.czkatran.czKatranService/delHealthcheckerDst", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *czKatranServiceClient) GetHealthcheckersDst(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HcMap, error) {
	out := new(HcMap)
	err := c.cc.Invoke(ctx, "/lb.czkatran.czKatranService/getHealthcheckersDst", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CzKatranServiceServer is the server API for CzKatranService service.
// All implementations must embed UnimplementedCzKatranServiceServer
// for forward compatibility
type CzKatranServiceServer interface {
	ChangeMac(context.Context, *Mac) (*Bool, error)
	GetMac(context.Context, *Empty) (*Mac, error)
	AddVip(context.Context, *VipMeta) (*Bool, error)
	DelVip(context.Context, *Vip) (*Bool, error)
	GetAllVips(context.Context, *Empty) (*Vips, error)
	ModifyVip(context.Context, *VipMeta) (*Bool, error)
	ModifyReal(context.Context, *RealMeta) (*Bool, error)
	GetVipFlags(context.Context, *Vip) (*Flags, error)
	GetRealFlags(context.Context, *Real) (*Flags, error)
	AddRealForVip(context.Context, *RealForVip) (*Bool, error)
	DelRealForVip(context.Context, *RealForVip) (*Bool, error)
	ModifyRealsForVip(context.Context, *ModifiedRealForVip) (*Bool, error)
	GetRealsForVip(context.Context, *Vip) (*Reals, error)
	ModifyQuicRealsMapping(context.Context, *ModifiedQuicReals) (*Bool, error)
	GetQuicRealsMapping(context.Context, *Empty) (*QuicReals, error)
	GetStatsForVip(context.Context, *Vip) (*Stats, error)
	GetLruStats(context.Context, *Empty) (*Stats, error)
	GetLruMissStats(context.Context, *Empty) (*Stats, error)
	GetLruFailbackStats(context.Context, *Empty) (*Stats, error)
	GetIcmpTooBigStats(context.Context, *Empty) (*Stats, error)
	AddHealthcheckerDst(context.Context, *Healthcheck) (*Bool, error)
	DelHealthcheckerDst(context.Context, *Somark) (*Bool, error)
	GetHealthcheckersDst(context.Context, *Empty) (*HcMap, error)
	mustEmbedUnimplementedCzKatranServiceServer()
}

// UnimplementedCzKatranServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCzKatranServiceServer struct {
}

func (UnimplementedCzKatranServiceServer) ChangeMac(context.Context, *Mac) (*Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeMac not implemented")
}
func (UnimplementedCzKatranServiceServer) GetMac(context.Context, *Empty) (*Mac, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMac not implemented")
}
func (UnimplementedCzKatranServiceServer) AddVip(context.Context, *VipMeta) (*Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddVip not implemented")
}
func (UnimplementedCzKatranServiceServer) DelVip(context.Context, *Vip) (*Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelVip not implemented")
}
func (UnimplementedCzKatranServiceServer) GetAllVips(context.Context, *Empty) (*Vips, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllVips not implemented")
}
func (UnimplementedCzKatranServiceServer) ModifyVip(context.Context, *VipMeta) (*Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyVip not implemented")
}
func (UnimplementedCzKatranServiceServer) ModifyReal(context.Context, *RealMeta) (*Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyReal not implemented")
}
func (UnimplementedCzKatranServiceServer) GetVipFlags(context.Context, *Vip) (*Flags, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVipFlags not implemented")
}
func (UnimplementedCzKatranServiceServer) GetRealFlags(context.Context, *Real) (*Flags, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRealFlags not implemented")
}
func (UnimplementedCzKatranServiceServer) AddRealForVip(context.Context, *RealForVip) (*Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRealForVip not implemented")
}
func (UnimplementedCzKatranServiceServer) DelRealForVip(context.Context, *RealForVip) (*Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelRealForVip not implemented")
}
func (UnimplementedCzKatranServiceServer) ModifyRealsForVip(context.Context, *ModifiedRealForVip) (*Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyRealsForVip not implemented")
}
func (UnimplementedCzKatranServiceServer) GetRealsForVip(context.Context, *Vip) (*Reals, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRealsForVip not implemented")
}
func (UnimplementedCzKatranServiceServer) ModifyQuicRealsMapping(context.Context, *ModifiedQuicReals) (*Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyQuicRealsMapping not implemented")
}
func (UnimplementedCzKatranServiceServer) GetQuicRealsMapping(context.Context, *Empty) (*QuicReals, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuicRealsMapping not implemented")
}
func (UnimplementedCzKatranServiceServer) GetStatsForVip(context.Context, *Vip) (*Stats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatsForVip not implemented")
}
func (UnimplementedCzKatranServiceServer) GetLruStats(context.Context, *Empty) (*Stats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLruStats not implemented")
}
func (UnimplementedCzKatranServiceServer) GetLruMissStats(context.Context, *Empty) (*Stats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLruMissStats not implemented")
}
func (UnimplementedCzKatranServiceServer) GetLruFailbackStats(context.Context, *Empty) (*Stats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLruFailbackStats not implemented")
}
func (UnimplementedCzKatranServiceServer) GetIcmpTooBigStats(context.Context, *Empty) (*Stats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIcmpTooBigStats not implemented")
}
func (UnimplementedCzKatranServiceServer) AddHealthcheckerDst(context.Context, *Healthcheck) (*Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddHealthcheckerDst not implemented")
}
func (UnimplementedCzKatranServiceServer) DelHealthcheckerDst(context.Context, *Somark) (*Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelHealthcheckerDst not implemented")
}
func (UnimplementedCzKatranServiceServer) GetHealthcheckersDst(context.Context, *Empty) (*HcMap, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHealthcheckersDst not implemented")
}
func (UnimplementedCzKatranServiceServer) mustEmbedUnimplementedCzKatranServiceServer() {}

// UnsafeCzKatranServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CzKatranServiceServer will
// result in compilation errors.
type UnsafeCzKatranServiceServer interface {
	mustEmbedUnimplementedCzKatranServiceServer()
}

func RegisterCzKatranServiceServer(s grpc.ServiceRegistrar, srv CzKatranServiceServer) {
	s.RegisterService(&CzKatranService_ServiceDesc, srv)
}

func _CzKatranService_ChangeMac_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Mac)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CzKatranServiceServer).ChangeMac(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lb.czkatran.czKatranService/changeMac",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CzKatranServiceServer).ChangeMac(ctx, req.(*Mac))
	}
	return interceptor(ctx, in, info, handler)
}

func _CzKatranService_GetMac_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CzKatranServiceServer).GetMac(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lb.czkatran.czKatranService/getMac",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CzKatranServiceServer).GetMac(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CzKatranService_AddVip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VipMeta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CzKatranServiceServer).AddVip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lb.czkatran.czKatranService/addVip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CzKatranServiceServer).AddVip(ctx, req.(*VipMeta))
	}
	return interceptor(ctx, in, info, handler)
}

func _CzKatranService_DelVip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Vip)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CzKatranServiceServer).DelVip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lb.czkatran.czKatranService/delVip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CzKatranServiceServer).DelVip(ctx, req.(*Vip))
	}
	return interceptor(ctx, in, info, handler)
}

func _CzKatranService_GetAllVips_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CzKatranServiceServer).GetAllVips(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lb.czkatran.czKatranService/getAllVips",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CzKatranServiceServer).GetAllVips(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CzKatranService_ModifyVip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VipMeta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CzKatranServiceServer).ModifyVip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lb.czkatran.czKatranService/modifyVip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CzKatranServiceServer).ModifyVip(ctx, req.(*VipMeta))
	}
	return interceptor(ctx, in, info, handler)
}

func _CzKatranService_ModifyReal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RealMeta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CzKatranServiceServer).ModifyReal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lb.czkatran.czKatranService/modifyReal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CzKatranServiceServer).ModifyReal(ctx, req.(*RealMeta))
	}
	return interceptor(ctx, in, info, handler)
}

func _CzKatranService_GetVipFlags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Vip)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CzKatranServiceServer).GetVipFlags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lb.czkatran.czKatranService/getVipFlags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CzKatranServiceServer).GetVipFlags(ctx, req.(*Vip))
	}
	return interceptor(ctx, in, info, handler)
}

func _CzKatranService_GetRealFlags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Real)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CzKatranServiceServer).GetRealFlags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lb.czkatran.czKatranService/getRealFlags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CzKatranServiceServer).GetRealFlags(ctx, req.(*Real))
	}
	return interceptor(ctx, in, info, handler)
}

func _CzKatranService_AddRealForVip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RealForVip)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CzKatranServiceServer).AddRealForVip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lb.czkatran.czKatranService/addRealForVip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CzKatranServiceServer).AddRealForVip(ctx, req.(*RealForVip))
	}
	return interceptor(ctx, in, info, handler)
}

func _CzKatranService_DelRealForVip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RealForVip)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CzKatranServiceServer).DelRealForVip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lb.czkatran.czKatranService/delRealForVip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CzKatranServiceServer).DelRealForVip(ctx, req.(*RealForVip))
	}
	return interceptor(ctx, in, info, handler)
}

func _CzKatranService_ModifyRealsForVip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifiedRealForVip)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CzKatranServiceServer).ModifyRealsForVip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lb.czkatran.czKatranService/modifyRealsForVip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CzKatranServiceServer).ModifyRealsForVip(ctx, req.(*ModifiedRealForVip))
	}
	return interceptor(ctx, in, info, handler)
}

func _CzKatranService_GetRealsForVip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Vip)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CzKatranServiceServer).GetRealsForVip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lb.czkatran.czKatranService/getRealsForVip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CzKatranServiceServer).GetRealsForVip(ctx, req.(*Vip))
	}
	return interceptor(ctx, in, info, handler)
}

func _CzKatranService_ModifyQuicRealsMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifiedQuicReals)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CzKatranServiceServer).ModifyQuicRealsMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lb.czkatran.czKatranService/modifyQuicRealsMapping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CzKatranServiceServer).ModifyQuicRealsMapping(ctx, req.(*ModifiedQuicReals))
	}
	return interceptor(ctx, in, info, handler)
}

func _CzKatranService_GetQuicRealsMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CzKatranServiceServer).GetQuicRealsMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lb.czkatran.czKatranService/getQuicRealsMapping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CzKatranServiceServer).GetQuicRealsMapping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CzKatranService_GetStatsForVip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Vip)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CzKatranServiceServer).GetStatsForVip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lb.czkatran.czKatranService/getStatsForVip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CzKatranServiceServer).GetStatsForVip(ctx, req.(*Vip))
	}
	return interceptor(ctx, in, info, handler)
}

func _CzKatranService_GetLruStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CzKatranServiceServer).GetLruStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lb.czkatran.czKatranService/getLruStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CzKatranServiceServer).GetLruStats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CzKatranService_GetLruMissStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CzKatranServiceServer).GetLruMissStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lb.czkatran.czKatranService/getLruMissStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CzKatranServiceServer).GetLruMissStats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CzKatranService_GetLruFailbackStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CzKatranServiceServer).GetLruFailbackStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lb.czkatran.czKatranService/getLruFailbackStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CzKatranServiceServer).GetLruFailbackStats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CzKatranService_GetIcmpTooBigStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CzKatranServiceServer).GetIcmpTooBigStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lb.czkatran.czKatranService/getIcmpTooBigStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CzKatranServiceServer).GetIcmpTooBigStats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CzKatranService_AddHealthcheckerDst_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Healthcheck)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CzKatranServiceServer).AddHealthcheckerDst(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lb.czkatran.czKatranService/addHealthcheckerDst",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CzKatranServiceServer).AddHealthcheckerDst(ctx, req.(*Healthcheck))
	}
	return interceptor(ctx, in, info, handler)
}

func _CzKatranService_DelHealthcheckerDst_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Somark)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CzKatranServiceServer).DelHealthcheckerDst(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lb.czkatran.czKatranService/delHealthcheckerDst",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CzKatranServiceServer).DelHealthcheckerDst(ctx, req.(*Somark))
	}
	return interceptor(ctx, in, info, handler)
}

func _CzKatranService_GetHealthcheckersDst_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CzKatranServiceServer).GetHealthcheckersDst(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lb.czkatran.czKatranService/getHealthcheckersDst",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CzKatranServiceServer).GetHealthcheckersDst(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// CzKatranService_ServiceDesc is the grpc.ServiceDesc for CzKatranService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CzKatranService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lb.czkatran.czKatranService",
	HandlerType: (*CzKatranServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "changeMac",
			Handler:    _CzKatranService_ChangeMac_Handler,
		},
		{
			MethodName: "getMac",
			Handler:    _CzKatranService_GetMac_Handler,
		},
		{
			MethodName: "addVip",
			Handler:    _CzKatranService_AddVip_Handler,
		},
		{
			MethodName: "delVip",
			Handler:    _CzKatranService_DelVip_Handler,
		},
		{
			MethodName: "getAllVips",
			Handler:    _CzKatranService_GetAllVips_Handler,
		},
		{
			MethodName: "modifyVip",
			Handler:    _CzKatranService_ModifyVip_Handler,
		},
		{
			MethodName: "modifyReal",
			Handler:    _CzKatranService_ModifyReal_Handler,
		},
		{
			MethodName: "getVipFlags",
			Handler:    _CzKatranService_GetVipFlags_Handler,
		},
		{
			MethodName: "getRealFlags",
			Handler:    _CzKatranService_GetRealFlags_Handler,
		},
		{
			MethodName: "addRealForVip",
			Handler:    _CzKatranService_AddRealForVip_Handler,
		},
		{
			MethodName: "delRealForVip",
			Handler:    _CzKatranService_DelRealForVip_Handler,
		},
		{
			MethodName: "modifyRealsForVip",
			Handler:    _CzKatranService_ModifyRealsForVip_Handler,
		},
		{
			MethodName: "getRealsForVip",
			Handler:    _CzKatranService_GetRealsForVip_Handler,
		},
		{
			MethodName: "modifyQuicRealsMapping",
			Handler:    _CzKatranService_ModifyQuicRealsMapping_Handler,
		},
		{
			MethodName: "getQuicRealsMapping",
			Handler:    _CzKatranService_GetQuicRealsMapping_Handler,
		},
		{
			MethodName: "getStatsForVip",
			Handler:    _CzKatranService_GetStatsForVip_Handler,
		},
		{
			MethodName: "getLruStats",
			Handler:    _CzKatranService_GetLruStats_Handler,
		},
		{
			MethodName: "getLruMissStats",
			Handler:    _CzKatranService_GetLruMissStats_Handler,
		},
		{
			MethodName: "getLruFailbackStats",
			Handler:    _CzKatranService_GetLruFailbackStats_Handler,
		},
		{
			MethodName: "getIcmpTooBigStats",
			Handler:    _CzKatranService_GetIcmpTooBigStats_Handler,
		},
		{
			MethodName: "addHealthcheckerDst",
			Handler:    _CzKatranService_AddHealthcheckerDst_Handler,
		},
		{
			MethodName: "delHealthcheckerDst",
			Handler:    _CzKatranService_DelHealthcheckerDst_Handler,
		},
		{
			MethodName: "getHealthcheckersDst",
			Handler:    _CzKatranService_GetHealthcheckersDst_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "czkatran.proto",
}
